version: "3.9"
services:
  mysql:
    image: mysql:8.0   # Use the desired version of MySQL
    container_name: mysql-docker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Replace with your secure root password
      MYSQL_DATABASE: testdb              # Initial database
      MYSQL_USER: testuser                # Non-root user
      MYSQL_PASSWORD: testpassword        # Password for the non-root user
    ports:
      - "3306:3306"  # Exposes MySQL on port 3306
    volumes:
      - mysql_data:/var/lib/mysql  # Persistent storage for database files

volumes:
  mysql_data:
